import type { Metadata } from "next";
import { Montserrat, Nunito_Sans } from 'next/font/google';

import "./globals.css";

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
});

const nunitoSans = Nunito_Sans({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: "SeptaGreen Africa",
  keywords: [
    "SeptaGreen",
    "Africa",
    "Software Development",
    "Cybersecurity",
    "Data Science",
    "Artificial Intelligence",
    "Machine Learning",
    "Web Development",
    "Technology",
    "Innovation",
    "Community Engagement",
  ],
  icons: "/logo.png",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={nunitoSans.className}
      >
        {children}
      </body>
    </html>
  );
}
